# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pixelfs < Formula
  desc "A cross-device file system, Transfer files based on s3-protocol."
  homepage "https://github.com/pixelfs/pixelfs"
  version "1.0.0"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/pixelfs/pixelfs/releases/download/v1.0.0/pixelfs_darwin_amd64_1.0.0.tar.gz"
      sha256 "f5f12e4fe974f551fc5c27ab4f1133fc26beb212a4a0ddbf1b92def4cbc18d86"

      def install
        bin.install "pixelfs"
        bash_completion.install "completions/bash_autocomplete" => "pixelfs"
        zsh_completion.install "completions/zsh_autocomplete" => "_pixelfs"
      end
    end
    on_arm do
      url "https://github.com/pixelfs/pixelfs/releases/download/v1.0.0/pixelfs_darwin_arm64_1.0.0.tar.gz"
      sha256 "9eae336456bc08cba2bf261a62862a3ac4f08095e76406b108de976c9699da57"

      def install
        bin.install "pixelfs"
        bash_completion.install "completions/bash_autocomplete" => "pixelfs"
        zsh_completion.install "completions/zsh_autocomplete" => "_pixelfs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pixelfs/pixelfs/releases/download/v1.0.0/pixelfs_linux_amd64_1.0.0.tar.gz"
        sha256 "da14cdc6d12f618dc8b0fdfaef5145405cef6f0d62d7ffee950f6d50c2543f76"

        def install
          bin.install "pixelfs"
          bash_completion.install "completions/bash_autocomplete" => "pixelfs"
          zsh_completion.install "completions/zsh_autocomplete" => "_pixelfs"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/pixelfs/pixelfs/releases/download/v1.0.0/pixelfs_linux_armv7_1.0.0.tar.gz"
        sha256 "a8645662470ecfea3cfabd763264300f7e7745f7553cf9d2133cf5f9188e9467"

        def install
          bin.install "pixelfs"
          bash_completion.install "completions/bash_autocomplete" => "pixelfs"
          zsh_completion.install "completions/zsh_autocomplete" => "_pixelfs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pixelfs/pixelfs/releases/download/v1.0.0/pixelfs_linux_arm64_1.0.0.tar.gz"
        sha256 "1e3e94a7a64b9b760384ae2341abbceba21413b5be5e0c963e63c5011cd2ae64"

        def install
          bin.install "pixelfs"
          bash_completion.install "completions/bash_autocomplete" => "pixelfs"
          zsh_completion.install "completions/zsh_autocomplete" => "_pixelfs"
        end
      end
    end
  end

  service do
    run [opt_bin/"pixelfs", "daemon"]
    keep_alive true
  end

  test do
    system "#{bin}/pixelfs version"
  end
end
